//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTInventarios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBINVENTARIOSEntitiess : DbContext
    {
        public DBINVENTARIOSEntitiess()
            : base("name=DBINVENTARIOSEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ZT_CAT_ALMACENES> ZT_CAT_ALMACENES { get; set; }
        public virtual DbSet<ZT_CAT_CEDIS> ZT_CAT_CEDIS { get; set; }
        public virtual DbSet<ZT_CAT_PRODUCTOS> ZT_CAT_PRODUCTOS { get; set; }
        public virtual DbSet<ZT_CAT_UNIDAD_MEDIDAS> ZT_CAT_UNIDAD_MEDIDAS { get; set; }
        public virtual DbSet<ZT_INVENTARIOS> ZT_INVENTARIOS { get; set; }
        public virtual DbSet<ZT_INVENTARIOS_CONTEOS> ZT_INVENTARIOS_CONTEOS { get; set; }
        public virtual DbSet<ZT_INVENTARIOS_DET> ZT_INVENTARIOS_DET { get; set; }
    }
}
