//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTInventarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZT_INVENTARIOS_DET
    {
        public int Id { get; set; }
        public string IdInventario { get; set; }
        public string SKU { get; set; }
        public string Material { get; set; }
        public Nullable<double> CantTeorica { get; set; }
        public Nullable<double> CantFisica { get; set; }
        public Nullable<double> Diferencia { get; set; }
        public string UMedida { get; set; }
        public string FechaReg { get; set; }
        public string UsuarioReg { get; set; }
        public string FechaUltMod { get; set; }
        public string UsuarioMod { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<bool> Borrado { get; set; }
    }
}
