//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RESTInventarios
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZT_INVENTARIOS_CONTEOS
    {
        public int Id { get; set; }
        public string IdInventario { get; set; }
        public string SKU { get; set; }
        public Nullable<int> IdConteo { get; set; }
        public string IdUbicacion { get; set; }
        public string IdCEDI { get; set; }
        public string IdAlmacen { get; set; }
        public string Almacen { get; set; }
        public string Lote { get; set; }
        public string CodBarras { get; set; }
        public string Material { get; set; }
        public Nullable<double> CantFisica { get; set; }
        public string IdUMedida { get; set; }
        public Nullable<double> CantidadPZA { get; set; }
        public string FechaReg { get; set; }
        public string HoraReg { get; set; }
        public string FechaUltMod { get; set; }
        public string HoraUltMod { get; set; }
        public string UsuarioReg { get; set; }
    }
}
